# Generated by Django 4.2.2 on 2023-09-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0002_remove_vehiclemaintenance_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('commercial_invoice', 'Commercial Invoice'), ('other_invoice', 'Other Invoice')], default='commercial_invoice', max_length=50)),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('client_information', models.TextField()),
                ('invoice_object', models.TextField(help_text='Reason for the invoice')),
                ('invoice_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss')], max_length=1000, null=True, verbose_name='Title')),
                ('first_name', models.CharField(max_length=1000, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=11000, null=True, verbose_name='Last Name')),
                ('biginning_date', models.DateField(blank=True, null=True, verbose_name='Beginning date of service')),
                ('employee_no', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Employee number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=1000, null=True, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Email address')),
                ('emergency_phone', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Emergency Phone')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='nationality')),
                ('id_card', models.CharField(blank=True, max_length=1000, null=True, verbose_name='NID NUMBER')),
                ('place_of_issue', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Place of issue')),
                ('Insurance_number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Insurance Number ')),
                ('passport_photo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='employees/photos/', verbose_name='Passport Photo')),
                ('employee_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank')),
                ('bank_account', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Account Number')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow(er)'), ('divorced', 'Divorced')], max_length=1000, null=True, verbose_name='Maritial status')),
                ('position', models.CharField(help_text='CEO, Secretariat,accountant,internee', max_length=100, null=True, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Staff ',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(null=True, upload_to='vehicle', verbose_name='Picture')),
                ('brand', models.CharField(max_length=200, verbose_name='Brand')),
                ('car_model', models.CharField(max_length=200, verbose_name='Car Model ')),
                ('year', models.PositiveIntegerField(verbose_name='Year ')),
                ('mileage', models.PositiveIntegerField(verbose_name='MileAge')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('plate', models.CharField(max_length=17, null=True, unique=True, verbose_name='Plate')),
                ('insurance_company', models.CharField(max_length=200, verbose_name='Insurance Company')),
                ('insurance_policy_number', models.CharField(max_length=100, unique=True, verbose_name='Insurance Policy Number')),
                ('current_service_schedule', models.DateField(verbose_name='Current Service Schedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiclemaintenance',
            name='parts_used',
        ),
        migrations.AlterField(
            model_name='fundmanagement',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='fundmanagement',
            name='entries',
            field=models.TextField(verbose_name='Entries'),
        ),
        migrations.AlterField(
            model_name='fundmanagement',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='fundmanagement',
            name='quantities',
            field=models.PositiveIntegerField(verbose_name='Quantities'),
        ),
        migrations.AlterField(
            model_name='fundmanagement',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='fundmanagement',
            name='transaction_date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='maintenance_comments',
            field=models.TextField(null=True, verbose_name='Maintenance Comments '),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='maintenance_date',
            field=models.DateField(verbose_name='Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='service_type',
            field=models.CharField(max_length=200, verbose_name='Service Type '),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='vehicle_picture',
            field=models.FileField(null=True, upload_to='Vehicle_Maintenance_Picture', verbose_name='Vehicle Picture'),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designations', models.CharField(max_length=255)),
                ('quantity_or_days', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mosaic_app.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_status', models.CharField(choices=[['sent', 'Sent'], ['delivered', 'Delivered'], ['seen', 'Seen']], default='sent', max_length=10, verbose_name='Message Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='mosaic_app.staff', verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='mosaic_app.staff', verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic_app.vehicle', verbose_name='Vehicle'),
        ),
        migrations.DeleteModel(
            name='VehicleManagement',
        ),
    ]
