# Generated by Django 4.2.2 on 2023-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0007_alter_chat_reference_code_alter_chathistory_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='vehicle', verbose_name='Picture'),
        ),
    ]
