# Generated by Django 3.2.18 on 2023-09-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0009_auto_20230907_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[['unpaid', 'Unpaid'], ['paid', 'Paid']], default='unpaid', max_length=50, verbose_name='Status'),
        ),
    ]
