# Generated by Django 3.2.18 on 2023-10-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0012_invoice_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundmanagement',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='fundmanagement',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='fundmanagement',
            name='total',
        ),
        migrations.RemoveField(
            model_name='fundmanagement',
            name='transaction_date',
        ),
        migrations.CreateModel(
            name='FundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('unit_price', models.CharField(max_length=50, verbose_name='Unit price')),
                ('total', models.CharField(max_length=50, verbose_name='Total')),
                ('observation', models.CharField(max_length=255, verbose_name='Observation')),
                ('fundmanagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mosaic_app.fundmanagement', verbose_name='Fund Management')),
            ],
            options={
                'verbose_name': 'Fund Item',
                'verbose_name_plural': 'Fund Items',
                'db_table': 'fund_items',
                'managed': True,
            },
        ),
    ]
