# Generated by Django 4.2.2 on 2023-08-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('transaction_date', models.DateField()),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('entries', models.TextField()),
                ('quantities', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Brand')),
                ('car_model', models.CharField(max_length=200, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('insurance_company', models.CharField(max_length=200)),
                ('insurance_policy_number', models.CharField(max_length=100, unique=True)),
                ('current_service_schedule', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('service_type', models.CharField(max_length=200)),
                ('parts_used', models.TextField()),
                ('notes', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic_app.vehiclemanagement')),
            ],
        ),
    ]
