# Generated by Django 4.2.2 on 2023-09-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mosaic_app', '0006_alter_chat_options_alter_fundmanagement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reference_code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Reference code'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='mosaic_app.chat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_no',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Employee number'),
        ),
    ]
