# Generated by Django 3.2.18 on 2023-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0008_alter_vehicle_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='InvoiceItem',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.FileField(null=True, upload_to='vehicle', verbose_name='Picture'),
        ),
    ]
