# Generated by Django 3.2.18 on 2023-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0014_archiveddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddocument',
            name='document',
            field=models.FileField(upload_to='archived_documents/', verbose_name='Document'),
        ),
    ]
