# Generated by Django 3.2.18 on 2023-11-07 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mosaic_app', '0015_alter_archiveddocument_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funditem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='archiveddocument',
            name='uploaded_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='funditem',
            name='observation',
            field=models.CharField(blank='True', max_length=255, verbose_name='Observation'),
        ),
    ]
