# Generated by Django 4.2.2 on 2023-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaintenance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehiclemanagement',
            name='vin',
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='maintenance_comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='vehicle_picture',
            field=models.FileField(null=True, upload_to='vehicle under maintence', verbose_name='enter the vehicle under maintenance'),
        ),
        migrations.AddField(
            model_name='vehiclemanagement',
            name='picture',
            field=models.FileField(null=True, upload_to='vehicle', verbose_name='vehicle picture'),
        ),
        migrations.AddField(
            model_name='vehiclemanagement',
            name='plate',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
