# Generated by Django 4.2.2 on 2023-09-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0004_rename_chathistory_chat_alter_chat_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
