# Generated by Django 3.2.18 on 2023-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0010_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(null=True, verbose_name='Invoice Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_information',
            field=models.TextField(verbose_name='Client Information'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_location',
            field=models.CharField(max_length=255, verbose_name='Invoice Location'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_object',
            field=models.TextField(help_text='Reason for the invoice', verbose_name='Reason'),
        ),
    ]
