# Generated by Django 3.2.18 on 2023-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic_app', '0011_auto_20230908_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account'),
        ),
    ]
